config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reactions
  resources :comments
  resources :posts
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user, optional: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user if user_signed_in?

    respond_to do |format|
      if @comment.save
        # Redirigir al post asociado después de crear el comentario
        format.html { redirect_to post_path(@comment.post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to comments_path, status: :see_other }
      format.json { head :no_content }  # Para manejar la respuesta JSON
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Anonymous:</strong>
    <%= comment.anonymous %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :post_id, style: "display: block" %>
    <%= form.text_field :post_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :anonymous, style: "display: block" %>
    <%= form.check_box :anonymous %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>