config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reactions
  resources :comments
  resources :posts
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :set_reaction, only: %i[ show edit update destroy ]

  # GET /reactions or /reactions.json
  def index
    @reactions = Reaction.all
  end

  # GET /reactions/1 or /reactions/1.json
  def show
  end

  # GET /reactions/new
  def new
    @reaction = Reaction.new
  end

  # GET /reactions/1/edit
  def edit
  end

  # POST /reactions or /reactions.json
  def create
    @reaction = Reaction.new(reaction_params)

    respond_to do |format|
      if @reaction.save
        format.html { redirect_to @reaction, notice: "Reaction was successfully created." }
        format.json { render :show, status: :created, location: @reaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reactions/1 or /reactions/1.json
  def update
    respond_to do |format|
      if @reaction.update(reaction_params)
        format.html { redirect_to @reaction, notice: "Reaction was successfully updated." }
        format.json { render :show, status: :ok, location: @reaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reactions/1 or /reactions/1.json
  def destroy
    @reaction.destroy!

    respond_to do |format|
      format.html { redirect_to reactions_path, status: :see_other, notice: "Reaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reaction
      @reaction = Reaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reaction_params
      params.require(:reaction).permit(:user_id, :post_id, :like)
    end
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/reactions/_form.html.erb
<%= form_with(model: reaction) do |form| %>
  <% if reaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reaction.errors.count, "error") %> prohibited this reaction from being saved:</h2>

      <ul>
        <% reaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :post_id, style: "display: block" %>
    <%= form.text_field :post_id %>
  </div>

  <div>
    <%= form.label :like, style: "display: block" %>
    <%= form.check_box :like %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reactions/_reaction.html.erb
<div id="<%= dom_id reaction %>">
  <p>
    <strong>User:</strong>
    <%= reaction.user_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= reaction.post_id %>
  </p>

  <p>
    <strong>Like:</strong>
    <%= reaction.like %>
  </p>

</div>

app/views/reactions/edit.html.erb
<h1>Editing reaction</h1>

<%= render "form", reaction: @reaction %>

<br>

<div>
  <%= link_to "Show this reaction", @reaction %> |
  <%= link_to "Back to reactions", reactions_path %>
</div>

app/views/reactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reactions</h1>

<div id="reactions">
  <% @reactions.each do |reaction| %>
    <%= render reaction %>
    <p>
      <%= link_to "Show this reaction", reaction %>
    </p>
  <% end %>
</div>

<%= link_to "New reaction", new_reaction_path %>

app/views/reactions/new.html.erb
<h1>New reaction</h1>

<%= render "form", reaction: @reaction %>

<br>

<div>
  <%= link_to "Back to reactions", reactions_path %>
</div>

app/views/reactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reaction %>

<div>
  <%= link_to "Edit this reaction", edit_reaction_path(@reaction) %> |
  <%= link_to "Back to reactions", reactions_path %>

  <%= button_to "Destroy this reaction", @reaction, method: :delete %>
</div>